language: go
go:
  - "1.13"
  - "1.14"
script:
  - export GO111MODULE="on"
  - cd cmd
  - go install -v ./...
  - cd ..
  - qgo tutorial/
  - go install -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
