name: Bug Report
description: Report a bug in goplus/gop
labels: bug
body:
  - type: textarea
    id: problem
    attributes:
      label: What happened?
      description: |
        Please provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner.
    validations:
      required: true        

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true