name: Go+ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Compile gop and related tools
      run: go run cmd/install.go --build

    - name: Run testcases
      run: go run cmd/install.go --test

    - name: Codecov
      uses: codecov/codecov-action@v2
